### ISSUE TITLE
App error

### ISSUE THREAD

**Issue by andiwijayaid** [yysrll/todoList#1]
1. Empty list doesn't contain element at index 0. (TodoAdapter.kt:75)
2. Kenapa bisa ada akunnya orang lain? satu device di pakai dua orang?

**Comment by yysrll** [comment]
Masih bisa diperbaiki kak?
 Untuk yg nomor 2, kemarin saya diminta tolongi untuk push tugas senior kak
lalu saya lupa logout kemudian commit punya saya kak

Pada tanggal Sen, 1 Jun 2020 21:23, Andi Wijaya <notifications@github.com>
menulis:
